#ifndef	C__Code_C_openwide_link_proto_h
#define	C__Code_C_openwide_link_proto_h
#pragma once



/* Prototype file C:\Code\C\openwide\link_proto.h *
 * generated by Pro2 from files:
 * C:\Code\C\openwide\link.c
 * on Friday, 13 May 2005 */


// functions from file C:\Code\C\openwide\link.c //
int addFavourite(HWND hwnd, POWSharedData pow);
int addPlace(HWND hwnd, PFavLink plk);
void dbgLink(const char *szMsg, PFavLink plk);
int DLLEXPORT expandFaves(POWSharedData pow, int nFaves);
int   faveExists(POWSharedData pow, const char *szFave);
PFavLink findFaveByCmdID(POWSharedData pow, UINT uID);
PFavLink findFaveByPath(POWSharedData pow, const char *szFave);
PFavLink getNthFave(POWSharedData pow, int n);
int initPlaces(HWND hwnd);
int iterAddPlace(PFavLink pFav, HWND hwnd);
int  iterateFaves(POWSharedData pow, FPFaveIter f, void * pData);
int DLLEXPORT lockFaves(POWSharedData pow);
PFavLink DLLEXPORT newFav(POWSharedData pow, const char *szTxt);
void DLLEXPORT unlockFaves(POWSharedData pow);

#endif	// C__Code_C_openwide_link_proto_h
