#ifndef	C__Code_C_openwide_openwidedll_proto_h
#define	C__Code_C_openwide_openwidedll_proto_h
#pragma once



/* Prototype file C:\Code\C\openwide\openwidedll_proto.h *
 * generated by Pro2 from files:
 * C:\Code\C\openwide\openwidedll.c
 * on Wednesday, 11 May 2005 */


// functions from file C:\Code\C\openwide\openwidedll.c //
int addIcon2TB(HWND hwTB, HICON hIcn);
void dbg(char *szError, ...);
BOOL DLLEXPORT CALLBACK WINAPI DllMain(HINSTANCE hDLLInst, DWORD fdwReason, LPVOID lpvReserved);
DWORD DLLEXPORT GetDllVersion(LPCTSTR lpszDllName);
BOOL DLLEXPORT isWinXP(void);
POWSharedData lockSharedData(void);
int DLLEXPORT rmvHook(void);
int DLLEXPORT setHook(HWND hwLB);
int unlockSharedData(POWSharedData pow);

#endif	// C__Code_C_openwide_openwidedll_proto_h
