#ifndef	C__Data_Code_C_openwide_owSharedUtil_h
/**
 * @author  Luke Hudson
 * @licence GPL2
 */

#define	C__Data_Code_C_openwide_owSharedUtil_h
#pragma once

#include	<windows.h>

/* Prototype file C:\Data\Code\C\openwide\owSharedUtil.h *
 * generated by Pro2 from files:
 * C:\Data\Code\C\openwide\owSharedUtil.c
 * on Tuesday, 12 July 2005 */

typedef int (*RegValEnumProc)(HKEY hk, const TCHAR *keyName, DWORD dwType, LPVOID pparam);

/* Copied on : Wed Jul 13 23:04:03 2005 */
void dbg(char *szError, ...);
char * getDlgItemText(HWND hwnd, UINT uID);
DWORD GetDllVersion(LPCTSTR lpszDllName);
const char * geterrmsg(void);
BOOL isWinXP(void);
void regCloseKey(HKEY hk);
HKEY regCreateKey(HKEY hkParent, const char *szSubKey);
int regDeleteKey(HKEY hkParent, const char *szSubKey);
int regEnumValues(HKEY hkRoot, RegValEnumProc fp, LPVOID param);
DWORD regGetDWORD(HKEY hkRoot, const char *szValue, int *pSuccess);
int regGetMaxValueNameLength(HKEY hk, LPDWORD pValueDataLen);
HKEY regOpenKey(HKEY hkParent, const char *szSubKey);
BYTE *regReadBinaryData(HKEY hkRoot, const char *szValueName);
DWORD regReadDWORD(HKEY hkRoot, const char *szValueName, int *pSuccess);
char *regReadSZ(HKEY hk, const char *szValueName);
int regWriteBinaryData(HKEY hkRoot, const char *szValue, BYTE *buf, int bufSize );
int regWriteDWORD(HKEY hkRoot, const char *szValue, DWORD dwData);
int regWriteSZ(HKEY hkRoot, const char *szValueName, const char *szData);
void Warn(char *szError, ...);

#endif	// C__Data_Code_C_openwide_owSharedUtil_h
