#ifndef	C__Data_Code_C_openwide_winutil_proto_h
#define	C__Data_Code_C_openwide_winutil_proto_h
#pragma once



/* Prototype file C:\Data\Code\C\openwide\winutil_proto.h *
 * generated by Pro2 from files:
 * C:\Data\Code\C\openwide\winutil.c
 * on Friday, 13 May 2005 */


// functions from file C:\Data\Code\C\openwide\winutil.c //
int Add_TrayIcon(HICON hIcon, char *szTip, HWND hwnd, UINT uMsg, DWORD dwState);
HRESULT CreateLink(LPCSTR lpszPathObj, LPCSTR lpszPathLink, LPCSTR lpszDesc);
void dbg(char *szError, ...);
int  dlgUnits2Pix(HWND hwnd, int units, BOOL bHorz);
void EndTrayOperation(void);
void Error(char *szError, ...);
BOOL fileExists (const char *path);
int getDlgItemRect(HWND hwnd, UINT uID, LPRECT pr);
const char * geterrmsg(void);
const char * getLocalPath(const char *szAppend);
int  pix2DlgUnits(HWND hwnd, int pix, BOOL bHorz);
char *Prompt_File_Name(int iFlags, HWND hwOwner, const char *pszFilter, const char *pszTitle);
BOOL propSheet(HWND hwParent, const char *szTitle, PFNPROPSHEETCALLBACK pfInitFunc, int nPages, ...);
void regCloseKey(HKEY hk);
HKEY regCreateKey(HKEY hkParent, const char *szSubKey);
HKEY regOpenKey(HKEY hkParent, const char *szSubKey);
BYTE *regReadBinaryData(HKEY hkRoot, const char *szValueName);
DWORD regReadDWORD(HKEY hkRoot, const char *szValueName, int *pSuccess);
char *regReadSZ(HKEY hk, const char *szValueName);
int regWriteBinaryData(HKEY hkRoot, const char *szValue, void *buf, int bufSize );
int regWriteDWORD(HKEY hkRoot, const char *szValue, DWORD dwData);
int regWriteSZ(HKEY hkRoot, const char *szValueName, const char *szData);
int Rem_TrayIcon(HWND hwnd, UINT uMsg, DWORD dwState);
void Warn(char *szError, ...);

#endif	// C__Data_Code_C_openwide_winutil_proto_h
